from django.urls import path
from .views import (
    UpdateJiraIssues,
    GenerateSprintReport,
    SprintInfoView,
    JiraProjectRegistrationView,
    JiraReports,
    ReportDataSprint,
    GetKanbanIssues,
    CreateIssue,
    GetEpicIssues,
    VelocityReport,
    ScrumReport,
    DailyStatusReport,
    ViewBacklogs,
    GetIssue,
    BurnUpReport,
    BurnDownReport,
    GetIssuesDetails,
)

urlpatterns = [
    path("update_jira_issues/", UpdateJiraIssues.as_view(), name="update_jira_issues"),
    path(
        "generate_sprint_report/",
        GenerateSprintReport.as_view(),
        name="generate_sprint_report",
    ),
    path("sprint_data/", SprintInfoView.as_view(), name="SprintInfoView"),
    path(
        "project_registartion/",
        JiraProjectRegistrationView.as_view(),
        name="JiraProjectRegistrationView",
    ),
    path(
        "jiraReports/",
        JiraReports.as_view(),
        name="JiraReports",
    ),
    path(
        "datasprint/",
        ReportDataSprint.as_view(),
        name="datasprint",
    ),
    path(
        "createissue/",
        CreateIssue.as_view(),
        name="createissue",
    ),
    path(
        "getepicissues/",
        GetEpicIssues.as_view(),
        name="getepicissues",
    ),
    path(
        "velocityreport/",
        VelocityReport.as_view(),
        name="velocityreport",
    ),
    path(
        "getkanbanissues/",
        GetKanbanIssues.as_view(),
        name="getkanbanissues",
    ),
    path(
        "dailystatusreport/",
        DailyStatusReport.as_view(),
        name="dailystatusreport",
    ),
    path(
        "scrumreport/",
        ScrumReport.as_view(),
        name="scrumreport",
    ),
    path(
        "viewbacklog/",
        ViewBacklogs.as_view(),
        name="viewbacklog",
    ),
    path(
        "getissues/",
        GetIssue.as_view(),
        name="getissues",
    ),
    path(
        "burnupreport/",
        BurnUpReport.as_view(),
        name="burnupreport",
    ),
    path(
        "burndownreport/",
        BurnDownReport.as_view(),
        name="burndownreport",
    ),
    path(
        "getissuedetails/",
        GetIssuesDetails.as_view(),
        name="getissuedetails",
    ),
]
